on:
  #workflow_dispatch: # Enables manual triggering
  push:
    branches:
     - main
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.1
        with:
          docker_name: 'zaproxy/zap-stable'
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly set if needed
          target: 'http://134.33.240.44/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          upload_artifact: false
