on:
  workflow_dispatch: # Enables manual triggering

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'zaproxy/zap-stable'
          target: 'http://135.234.200.45/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
