name: ZAP Security Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  actions: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    container:
      image: zaproxy/zap-stable
      options: --user root -v /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create required directories
        run: |
          mkdir -p .zap
          touch .zap/rules.tsv
          chmod -R 777 .zap

      - name: Run ZAP Scan (No Artifacts)
        run: |
          zap-baseline.py -t http://134.33.240.44/ -a \
          -J zap_report.json -w zap_report.md -r zap_report.html \
          --hook=zap/outcome_hook.py
          
      - name: Upload scan results as artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: zap-scan-results
          path: |
            zap_report.*
            output.txt
